from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r"countries", views.CountryViewSet, basename="country")
router.register(r"specialities", views.SpecialityViewSet, basename="speciality")
router.register(r"plans", views.PlanViewSet, basename="plan")
router.register(r"roles", views.RoleViewSet, basename="role")
router.register(r"providers", views.ProviderViewSet, basename="provider")
router.register(r"patients", views.PatientViewSet, basename="patient")
router.register(r"nutrition", views.NutritionEntryViewSet, basename="nutrition")

urlpatterns = [
    path("health/", views.health),
    path("welcome/", views.api_welcome, name="api-welcome"),
    path("doctor-on-call/me/", views.doctor_on_call_me),
    path("doctor-on-call/sync/push/", views.doctor_on_call_sync_push),
    path("doctor-on-call/sync/<str:entity>/", views.doctor_on_call_sync_pull),
    path("auth/login/", views.auth_login),
    path("auth/register/", views.auth_register),
    path("auth/register-admin/", views.auth_register_admin),
    path("admin/users/create/", views.admin_create_user),
    path("auth/logout/", views.auth_logout),
    path("auth/delete-account/", views.auth_delete_account),
    path("users/me/", views.auth_delete_account),
    path("privacy/request-account-deletion/", views.auth_delete_account),
    path("auth/password-policy/", views.auth_password_policy),
    path("user-data/", views.user_data),
    path("feedback/context/", views.feedback_context),
    path("feedback/submit/", views.feedback_submit),
    path("hospitals/", views.hospitals_list),
    path("hospitals/search/", views.hospitals_search),
    path("hospitals/seed-demo/", views.hospitals_seed_demo),
    path("hospitals/<str:hospital_id>/", views.hospital_detail),
    path(
        "hospitals/<str:hospital_id>/ai-wait-time/",
        views.hospital_ai_wait_time,
    ),
    path(
        "hospitals/<str:hospital_id>/smart-wait-time/",
        views.hospital_smart_wait_time,
    ),
    path("er-wait-times/", views.er_wait_times),
    path("osm/search-hospitals/", views.osm_search),
    path("osm/system-status/", views.osm_status),
    path("tomtom/tiles/<int:z>/<int:x>/<int:y>.png", views.tomtom_tile),
    path("tomtom/status/", views.tomtom_status),
    path("tomtom/search-hospitals/", views.tomtom_search_hospitals),
    path("tomtom/geocode/", views.tomtom_geocode),
    path("tomtom/reverse-geocode/", views.tomtom_reverse_geocode),
    path("tomtom/route/", views.tomtom_route),
    path("map-config/", views.map_config),
    path("v1/courses/", views.courses_v1),
    path("patients-providers/", views.patients_providers),
    path("providers/seed-demo/", views.providers_seed_demo),
    path("providers/apply/", views.provider_apply),
    path("provider-types/", views.provider_types),
    path("reference/seed-all/", views.reference_seed_all),
    path("specialities/seed-avatars/", views.specialities_seed_avatars),
    path("registrations/pending/", views.registrations_pending),
    path("registrations/approve/", views.registrations_approve),
    path("imports/submit/", views.import_submit),
    path("imports/pending/", views.import_pending),
    path("imports/merge/", views.import_merge),
    path("appointments/mine/", views.appointment_list),
    path("appointments/all/", views.appointment_all),
    path("appointments/<int:pk>/", views.appointment_detail),
    path("appointments/", views.appointment_create),
    path("auth/change-password/", views.change_password),
    path("auth/password-reset/request/", views.password_reset_request),
    path("auth/password-reset/confirm/", views.password_reset_confirm),
    path("integrations/ollama-status/", views.ollama_status),
    path("integrations/ai-assist-status/", views.ai_assist_status),
    path("medical-records/ai-assist/", views.medical_records_ai_assist),
    path("medical-records/<str:record_id>/", views.medical_record_detail),
    path("medical-records/", views.medical_records_list),
    path("vitals/", views.vitals_list),
    path("invoices/", views.invoices_list),
    path("timezone/", views.timezone_list),
    path("settings/general/", views.general_settings),
    path("settings/general/<str:key>/", views.general_settings),
    path("documents/", views.patient_documents),
    path("documents/<int:doc_id>/", views.patient_document_detail),
    path("patient/me/", views.patient_me_update),
    path("billing/status/", views.billing_status),
    path("billing/checkout/", views.billing_checkout),
    path("billing/verify-store/", views.billing_verify_store),
    path("billing/webhook/", views.billing_webhook),
    path("billing/stripe-webhook/", views.stripe_billing_webhook),
    path("billing/admin/summary/", views.admin_platform_billing_summary),
    path("billing/doctor/stripe-connect/", views.doctor_stripe_connect_onboard),
    path("billing/doctor/stripe-connect/status/", views.doctor_stripe_connect_status),
    path("billing/doctor/summary/", views.doctor_billing_summary),
    path("billing/doctor/transactions/", views.doctor_transactions),
    path("billing/doctor/create-invoice/", views.doctor_create_invoice),
    path("billing/doctor/complimentary-visit/", views.doctor_create_invoice),
    path("billing/doctor/request-payout/", views.provider_request_payout),
    path("billing/patient/bills/", views.patient_bills),
    path("billing/patient/pay-bill/", views.patient_pay_bill),
    path("shares/mine/", views.shares_mine),
    path("shares/inbox/", views.shares_inbox),
    path("shares/triage/", views.shares_triage_create),
    path("shares/", views.shares_create),
    path("visit-notes/", views.visit_notes),
    path("shares/<int:share_id>/", views.shares_delete),
    path("shares/<int:share_id>/email/", views.shares_email_patient),
    path("", include(router.urls)),
]
