# Generated by Django 5.2.5 on 2026-05-06 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=32)),
                ('country_name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('discount', models.CharField(blank=True, max_length=64, null=True)),
                ('discount_date', models.DateField(blank=True, null=True)),
                ('number_appointments', models.CharField(max_length=64)),
                ('ai_bot', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_entries',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=512)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('identity_no', models.CharField(blank=True, max_length=255)),
                ('profile_status', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=64, unique=True)),
                ('profile_picture', models.CharField(blank=True, max_length=512)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('nationality', models.CharField(blank=True, max_length=128)),
                ('sub_specialization', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=512)),
                ('license_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('license_authority', models.CharField(blank=True, max_length=255)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('consultation_days', models.CharField(blank=True, max_length=255)),
                ('consultation_hours', models.JSONField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=64)),
                ('max_consultations_per_day', models.IntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consultation_type', models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('chat', 'chat'), ('in-person', 'in-person')], default='video', max_length=32)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=128)),
                ('consultation_duration', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'pending')], default='pending', max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('registered_date', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('approved', models.CharField(blank=True, max_length=64, null=True)),
                ('medium', models.CharField(blank=True, max_length=64, null=True)),
                ('review', models.CharField(blank=True, max_length=512, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.provider')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=255)),
                ('speciality_image', models.CharField(blank=True, max_length=512)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialities', to='emr.country')),
            ],
            options={
                'db_table': 'specialities',
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.speciality'),
        ),
    ]
