# Generated by Django 5.2.5 on 2026-05-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'general',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('facility_type', models.CharField(default='Hospital', max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('ai_rating', models.FloatField(blank=True, null=True)),
                ('wait_time_minutes', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('photo_url', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'timezone',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='emr.patient')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
    ]
