# Generated by Django 5.2.5 on 2026-05-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0002_general_hospital_timezone_invoices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_url", models.CharField(blank=True, max_length=1024)),
                ("source_system", models.CharField(blank=True, max_length=128)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("raw_payload", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="emr.patient",
                    ),
                ),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportInbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patient_email", models.EmailField(blank=True, max_length=254)),
                ("patient_hint", models.CharField(blank=True, max_length=255)),
                ("source_url", models.CharField(max_length=1024)),
                ("raw_payload", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "pending"), ("merged", "merged"), ("rejected", "rejected")],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_merges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_imports",
                        to="emr.patient",
                    ),
                ),
                (
                    "merged_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_imports",
                        to="emr.medicalrecord",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_inbox",
                "ordering": ["-id"],
            },
        ),
    ]

