# Generated by Django 5.2.14 on 2026-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0004_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(default='active', max_length=32)),
                ('description', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
    ]
