# Generated by Django 5.2.14 on 2026-05-08 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_alter_feedback_options_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_note', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('include_patient_email', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('viewed', 'viewed'), ('deleted', 'deleted')], default='sent', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='emr.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_inbox', to='emr.provider')),
            ],
            options={
                'db_table': 'patient_shares',
                'ordering': ['-id'],
            },
        ),
    ]
