# Generated by Django 5.2.14 on 2026-05-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0007_patientshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('canceled', 'canceled'), ('failed', 'failed')], default='pending', max_length=16)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='emr.patient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='emr.plan')),
            ],
            options={
                'db_table': 'patient_subscriptions',
                'ordering': ['-id'],
            },
        ),
    ]
