# Generated by opencode — RevenueCat + Doctor billing schema update

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0011_patient_provider_whatsapp'),
    ]

    operations = [
        # ── Update PatientSubscription: remove Stripe fields, add RevenueCat fields ──
        migrations.RemoveField(
            model_name='patientsubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='patientsubscription',
            name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='patientsubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='revenuecat_product_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='revenuecat_entitlement_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='platform',
            field=models.CharField(default='apple', help_text='apple or android', max_length=16),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='original_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='store_country',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='will_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='expires_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='patientsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # ── ProviderTransaction: tracks doctor→patient billing ──
        migrations.CreateModel(
            name='ProviderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('provider_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('refunded', 'refunded'), ('failed', 'failed')], default='pending', max_length=16)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='emr.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='emr.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='emr.provider')),
            ],
            options={
                'db_table': 'provider_transactions',
                'ordering': ['-id'],
            },
        ),

        # ── ProviderPayout: tracks doctor withdrawals ──
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed')], default='pending', max_length=16)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='emr.provider')),
            ],
            options={
                'db_table': 'provider_payouts',
                'ordering': ['-id'],
            },
        ),
    ]
