#!/usr/bin/env python3
"""Download Twemoji PNGs used by speciality avatars into flutter_emr/assets/twemoji/."""

from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "flutter_emr" / "assets" / "twemoji"
BASE = "https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72"

# Keep in sync with django_emr/emr/speciality_avatars.py
KEYWORD_ICONS: tuple[tuple[str, str], ...] = (
    ("allergy", "1f927"),
    ("immunology", "1f9fc"),
    ("cardio", "2764"),
    ("heart", "2764"),
    ("derma", "1f9fc"),
    ("skin", "1f9fc"),
    ("neuro", "1f9e0"),
    ("brain", "1f9e0"),
    ("pediatr", "1f476"),
    ("child", "1f476"),
    ("ortho", "1f9b5"),
    ("bone", "1f9b4"),
    ("eye", "1f441-fe0f"),
    ("ophthal", "1f441-fe0f"),
    ("radio", "1f4f7"),
    ("imaging", "1f4f7"),
    ("emergency", "1f691"),
    ("trauma", "1f691"),
    ("psych", "1f9d8"),
    ("mental", "1f9d8"),
    ("dent", "1f9b7"),
    ("nutrition", "1f96a"),
    ("diet", "1f96a"),
    ("surgery", "1fa7a"),
    ("surgical", "1fa7a"),
    ("family", "1f46a"),
    ("internal", "1f3e5"),
    ("medicine", "1f3e5"),
    ("anesth", "1f48a"),
    ("pathology", "1f52c"),
    ("lab", "1f52c"),
    ("urology", "1f4a7"),
    ("oncology", "1f380"),
    ("cancer", "1f380"),
    ("gastro", "1f957"),
    ("pulmon", "1fac1"),
    ("lung", "1fac1"),
    ("obstet", "1f476"),
    ("gynec", "1f9ba"),
    ("women", "1f9ba"),
    ("geriatr", "1f9d3"),
    ("elder", "1f9d3"),
    ("sport", "26bd"),
    ("pain", "1f915"),
    ("sleep", "1f634"),
    ("endocrin", "1f9ec"),
    ("diabetes", "1f9ec"),
    ("infect", "1f9a0"),
    ("virus", "1f9a0"),
    ("occupational", "1f477"),
    ("plastic", "1f485"),
    ("vascular", "1fa78"),
    ("nephro", "1f9fd"),
    ("kidney", "1f9fd"),
    ("hepat", "1f9a0"),
    ("liver", "1f9a0"),
    ("ent", "1f442"),
    ("otolaryng", "1f442"),
    ("chiropractic", "1f9b5"),
    ("podiatr", "1f9b6"),
    ("foot", "1f9b6"),
    ("hematology", "1fa78"),
    ("blood", "1fa78"),
    ("rheumat", "1f9b4"),
    ("critical", "1f691"),
    ("icu", "1f691"),
    ("neonatal", "1f476"),
    ("rehab", "1f9d8"),
    ("physical therapy", "1f9d8"),
    ("telemedicine", "1f4f1"),
    ("genetic", "1f9ec"),
)

FALLBACK = ("1fa7a", "1f3e5", "1f48a", "2764", "1f9e0", "1f52c")

PRESET_CATALOG = (
    ("Stethoscope", "1fa7a"),
    ("Hospital", "1f3e5"),
    ("Pill", "1f48a"),
    ("Heart", "2764"),
    ("Brain", "1f9e0"),
    ("Microscope", "1f52c"),
)


def collect_codes() -> set[str]:
    codes: set[str] = set(FALLBACK)
    for _, code in KEYWORD_ICONS:
        codes.add(code.lower())
    for _, code in PRESET_CATALOG:
        codes.add(code.lower())
    return codes


def download(code: str) -> bool:
    dest = OUT / f"{code}.png"
    if dest.is_file() and dest.stat().st_size > 64:
        return True
    urls = [f"{BASE}/{code}.png"]
    if "-fe0f" in code:
        urls.append(f"{BASE}/{code.split('-')[0]}.png")
    req_headers = {"User-Agent": "DocOnCall-EMR/1.0"}
    for url in urls:
        req = urllib.request.Request(url, headers=req_headers)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = resp.read()
            if len(data) < 64:
                continue
            dest.write_bytes(data)
            return True
        except Exception:
            continue
    print(f"  FAIL {code}")
    return False


def emit_dart(codes: set[str]) -> None:
    dart = ROOT / "flutter_emr" / "lib" / "utils" / "twemoji_assets.dart"
    keywords = []
    for kw, code in KEYWORD_ICONS:
        keywords.append((kw, code.lower()))
    presets = [(label, code.lower()) for label, code in PRESET_CATALOG]

    kw_lines = ",\n".join(f"    (keyword: '{k}', code: '{c}')" for k, c in keywords)
    preset_lines = ",\n".join(f"    (label: '{l}', code: '{c}')" for l, c in presets)
    code_list = ",\n".join(f"    '{c}'" for c in sorted(codes))

    fb = ", ".join(f"'{c}'" for c in FALLBACK)
    content = f'''// GENERATED by scripts/download_twemoji_assets.py — do not edit by hand.

/// Local Twemoji PNGs under [assets/twemoji/] (no CDN at runtime).
abstract final class TwemojiAssets {{
  static const basePath = 'assets/twemoji';

  static const Set<String> codes = {{
{code_list}
  }};

  static const List<({{String keyword, String code}})> keywordIcons = [
{kw_lines}
  ];

  static const List<({{String label, String code}})> presetCatalog = [
{preset_lines}
  ];

  static const List<String> fallbackCodes = [{fb}];

  static String pathForCode(String code) => '$basePath/${{code.toLowerCase()}}.png';

  static bool hasCode(String code) => codes.contains(code.toLowerCase());

  /// `asset:twemoji/2764.png`, CDN URL, or bare code `2764`.
  static String? resolveAssetPath(String? raw) {{
    final s = (raw ?? '').trim();
    if (s.isEmpty) return null;
    if (s.startsWith('asset:twemoji/')) {{
      final file = s.split('/').last;
      final code = file.replaceAll('.png', '');
      return hasCode(code) ? pathForCode(code) : null;
    }}
    final m = RegExp(r'/72x72/([a-f0-9-]+)\\.png', caseSensitive: false).firstMatch(s);
    if (m != null) {{
      final code = m.group(1)!;
      return hasCode(code) ? pathForCode(code) : null;
    }}
    if (hasCode(s)) return pathForCode(s);
    return null;
  }}

  static String? codeForSpecialityName(String name) {{
    final n = name.toLowerCase();
    for (final e in keywordIcons) {{
      if (n.contains(e.keyword)) return e.code;
    }}
    if (fallbackCodes.isEmpty) return null;
    return fallbackCodes[name.hashCode.abs() % fallbackCodes.length];
  }}

  static String assetRefForCode(String code) => 'asset:twemoji/${{code.toLowerCase()}}.png';
}}
'''
    dart.write_text(content, encoding="utf-8")
    print(f"Wrote {dart}")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    codes = collect_codes()
    ok = 0
    for code in sorted(codes):
        if download(code):
            ok += 1
            print(f"  OK {code}")
    manifest = {"codes": sorted(codes), "count": ok}
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    emit_dart(codes)
    print(f"Downloaded {ok}/{len(codes)} → {OUT}")


if __name__ == "__main__":
    main()
