// GENERATED by scripts/download_twemoji_assets.py — do not edit by hand.

/// Local Twemoji PNGs under [assets/twemoji/] (no CDN at runtime).
abstract final class TwemojiAssets {
  static const basePath = 'assets/twemoji';

  static const Set<String> codes = {
    '1f380',
    '1f3e5',
    '1f441-fe0f',
    '1f442',
    '1f46a',
    '1f476',
    '1f477',
    '1f485',
    '1f48a',
    '1f4a7',
    '1f4f1',
    '1f4f7',
    '1f52c',
    '1f634',
    '1f691',
    '1f915',
    '1f927',
    '1f957',
    '1f96a',
    '1f9a0',
    '1f9b4',
    '1f9b5',
    '1f9b6',
    '1f9b7',
    '1f9ba',
    '1f9d3',
    '1f9d8',
    '1f9e0',
    '1f9ec',
    '1f9fc',
    '1f9fd',
    '1fa78',
    '1fa7a',
    '1fac1',
    '26bd',
    '2764'
  };

  static const List<({String keyword, String code})> keywordIcons = [
    (keyword: 'allergy', code: '1f927'),
    (keyword: 'immunology', code: '1f9fc'),
    (keyword: 'cardio', code: '2764'),
    (keyword: 'heart', code: '2764'),
    (keyword: 'derma', code: '1f9fc'),
    (keyword: 'skin', code: '1f9fc'),
    (keyword: 'neuro', code: '1f9e0'),
    (keyword: 'brain', code: '1f9e0'),
    (keyword: 'pediatr', code: '1f476'),
    (keyword: 'child', code: '1f476'),
    (keyword: 'ortho', code: '1f9b5'),
    (keyword: 'bone', code: '1f9b4'),
    (keyword: 'eye', code: '1f441-fe0f'),
    (keyword: 'ophthal', code: '1f441-fe0f'),
    (keyword: 'radio', code: '1f4f7'),
    (keyword: 'imaging', code: '1f4f7'),
    (keyword: 'emergency', code: '1f691'),
    (keyword: 'trauma', code: '1f691'),
    (keyword: 'psych', code: '1f9d8'),
    (keyword: 'mental', code: '1f9d8'),
    (keyword: 'dent', code: '1f9b7'),
    (keyword: 'nutrition', code: '1f96a'),
    (keyword: 'diet', code: '1f96a'),
    (keyword: 'surgery', code: '1fa7a'),
    (keyword: 'surgical', code: '1fa7a'),
    (keyword: 'family', code: '1f46a'),
    (keyword: 'internal', code: '1f3e5'),
    (keyword: 'medicine', code: '1f3e5'),
    (keyword: 'anesth', code: '1f48a'),
    (keyword: 'pathology', code: '1f52c'),
    (keyword: 'lab', code: '1f52c'),
    (keyword: 'urology', code: '1f4a7'),
    (keyword: 'oncology', code: '1f380'),
    (keyword: 'cancer', code: '1f380'),
    (keyword: 'gastro', code: '1f957'),
    (keyword: 'pulmon', code: '1fac1'),
    (keyword: 'lung', code: '1fac1'),
    (keyword: 'obstet', code: '1f476'),
    (keyword: 'gynec', code: '1f9ba'),
    (keyword: 'women', code: '1f9ba'),
    (keyword: 'geriatr', code: '1f9d3'),
    (keyword: 'elder', code: '1f9d3'),
    (keyword: 'sport', code: '26bd'),
    (keyword: 'pain', code: '1f915'),
    (keyword: 'sleep', code: '1f634'),
    (keyword: 'endocrin', code: '1f9ec'),
    (keyword: 'diabetes', code: '1f9ec'),
    (keyword: 'infect', code: '1f9a0'),
    (keyword: 'virus', code: '1f9a0'),
    (keyword: 'occupational', code: '1f477'),
    (keyword: 'plastic', code: '1f485'),
    (keyword: 'vascular', code: '1fa78'),
    (keyword: 'nephro', code: '1f9fd'),
    (keyword: 'kidney', code: '1f9fd'),
    (keyword: 'hepat', code: '1f9a0'),
    (keyword: 'liver', code: '1f9a0'),
    (keyword: 'ent', code: '1f442'),
    (keyword: 'otolaryng', code: '1f442'),
    (keyword: 'chiropractic', code: '1f9b5'),
    (keyword: 'podiatr', code: '1f9b6'),
    (keyword: 'foot', code: '1f9b6'),
    (keyword: 'hematology', code: '1fa78'),
    (keyword: 'blood', code: '1fa78'),
    (keyword: 'rheumat', code: '1f9b4'),
    (keyword: 'critical', code: '1f691'),
    (keyword: 'icu', code: '1f691'),
    (keyword: 'neonatal', code: '1f476'),
    (keyword: 'rehab', code: '1f9d8'),
    (keyword: 'physical therapy', code: '1f9d8'),
    (keyword: 'telemedicine', code: '1f4f1'),
    (keyword: 'genetic', code: '1f9ec')
  ];

  static const List<({String label, String code})> presetCatalog = [
    (label: 'Stethoscope', code: '1fa7a'),
    (label: 'Hospital', code: '1f3e5'),
    (label: 'Pill', code: '1f48a'),
    (label: 'Heart', code: '2764'),
    (label: 'Brain', code: '1f9e0'),
    (label: 'Microscope', code: '1f52c')
  ];

  static const List<String> fallbackCodes = ['1fa7a', '1f3e5', '1f48a', '2764', '1f9e0', '1f52c'];

  static String pathForCode(String code) => '$basePath/${code.toLowerCase()}.png';

  static bool hasCode(String code) => codes.contains(code.toLowerCase());

  /// `asset:twemoji/2764.png`, CDN URL, or bare code `2764`.
  static String? resolveAssetPath(String? raw) {
    final s = (raw ?? '').trim();
    if (s.isEmpty) return null;
    if (s.startsWith('asset:twemoji/')) {
      final file = s.split('/').last;
      final code = file.replaceAll('.png', '');
      return hasCode(code) ? pathForCode(code) : null;
    }
    final m = RegExp(r'/72x72/([a-f0-9-]+)\.png', caseSensitive: false).firstMatch(s);
    if (m != null) {
      final code = m.group(1)!;
      return hasCode(code) ? pathForCode(code) : null;
    }
    if (hasCode(s)) return pathForCode(s);
    return null;
  }

  static String? codeForSpecialityName(String name) {
    final n = name.toLowerCase();
    for (final e in keywordIcons) {
      if (n.contains(e.keyword)) return e.code;
    }
    if (fallbackCodes.isEmpty) return null;
    return fallbackCodes[name.hashCode.abs() % fallbackCodes.length];
  }

  static String assetRefForCode(String code) => 'asset:twemoji/${code.toLowerCase()}.png';
}
